##herramienta de desarrollo
##Crear un cliente especifico
GET http://localhost:5000/alumnos/

####
GET http://localhost:5000/alumnos/5096385

###
POST http://localhost:5000/alumnos
content-type: application/json

{
    "dni":50963852,
    "nombre": "Raul",
    "apellido": "Lopez",
    "email": "Raul.lopez@gmail.com"
}

###
PUT http://localhost:5000/alumnos/49963852
content-type: application/json

{
    "nombre": "Ramon",
    "apellido": "Lopez",
    "gmail": "Ramon.lopez@gmail.com"
    //"id_curso": 0,
  
}

###
DELETE http://localhost:5000/alumnos/2

