GET http://localhost:5000/profesores


###
GET http://localhost:5000/profesores/2

###
POST http://localhost:5000/profesores
content-type: application/json

{
    "nombre": "Carmen",
    "apellido": "Pizarro"
}

###
PUT http://localhost:5000/profesores/11
content-type: application/json

{
    "nombre": "Fermin",
    "apellido": "Lopez"
}

###
DELETE  http://localhost:5000/profesores/11