##herramienta de desarrollo
##Crear un cliente especifico
GET http://localhost:5000/alumnos

####
GET http://localhost:5000/alumnos/5

###
POST http://localhost:5000/alumnos
content-type: application/json

  {
    
      "nombre": "Ana",
      "apellido": "Martínez",
      "gmail": "ana.martinez@gmail.com",
      "gmail": "Jose.lopez@gmail.com",
    "id_curso": 0,
    "id_alumno":"dvfvfvfvfv"
    
 }

###
PUT http://localhost:5000/alumnos/2
content-type: application/json

{
    "nombre": "Jose",
    "apellido": "Lopez",
    "gmail": "Jose.lopez@gmail.com",
    "id_curso": 0
  
}

###
DELETE http://localhost:5000/alumnos/2

