##herramienta de desarrollo
##Crear un cliente especifico
GET http://localhost:5000/alumnos

####
GET http://localhost:5000/alumnos/3

###
POST http://localhost:5000/alumnos
content-type: application/json

  {
    
      "nombre": "Ana",
      "apellido": "Martínez",
      "gmail": "ana.martinez@gmail.com",
      "id_curso": 0
    
 }
